### ISSUE TITLE
docker-machine invalid parameter --debug

### ISSUE THREAD

**Issue by OneCricketeer** [garystafford/virtual-vehicles-docker#2]
Just pulled your code, ran through your script and got an error message at this line 

`docker-machine create --driver virtualbox test --debug`

That says

`Invalid command line. Found extra arguments [--debug]`

Here are my versions

``` sh
$ docker -v && docker-compose -v && \
    docker-machine -v && VBoxManage --version
Docker version 1.9.1, build a34a1d5
docker-compose version 1.5.2, build 7240ff3
docker-machine version 0.5.5, build 02c4254
5.0.12r104815
```

Moving `--debug` to immediately after `docker-machine` ran without error and created the machine. 

`docker-machine --debug create --driver virtualbox test`

**Comment by garystafford** [comment]
Thank you for noticing. I updated README.md.
