### ISSUE TITLE
Missing build.sh in logspout directory

### ISSUE THREAD

**Issue by ap1kenobi** [garystafford/virtual-vehicles-docker#3]
Why someone would want to pull latest code from their github repo when their container is used as base is beyond me, but I digress...

When trying to "compose up" logspout build triggers`ONBUILD COPY` in the original gliderlabs/logspout image, which is looking for modules.go and build.sh.  Modules.go is there but build.sh is missing.

**Comment by garystafford** [comment]
There is a bug with that image. I have fix I will send link to in later
repo.

**Comment by garystafford** [comment]
Updated several items in this project, including using a new logspout image (`amouat/logspout-logstash:latest`), which works better than original choice (`gliderlabs/logspout:master`). This image has several unresolved issues.
